[tool.poetry]
name = "like_basic"
version = "0.1.0"
description = ""
authors = ["rensatopc"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyfiglet = "^1.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
